url: https://tandinhlee.github.io
baseurl: ""

# Site settings
title: Dinh Le
email: tandinhlee@gmail.com
description: "Passionate in mobile development: applications and games and another crazy stuff"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Dinh Le
  pic: 1
  position: Indie Developer
  social:
    - title: twitter
      url: https://twitter.com/DinhLeTan
    - title: facebook
      url: https://www.facebook.com/tandinhlee
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/DinhLeTan
  - title: facebook
    url: https://twitter.com/DinhLeTan
  - title: bitbucket 
    url: http://bitbucket.org/tandinhlee
  - title: github
    url: http://github.com/tandinhlee

# Postal address (add as many lines as necessary)
address:
  - line: 21/2/9 Hong Lac Tan Binh Dist Ho Chi Minh City Vietnam
# Build settings
markdown: kramdown
permalink: pretty